Starter testing av Edith på jupyter-prod
Legger app.py koden over til en notebook og legger til kode for jupyterdash.
Kobler også Edith til potet og grovfor datasettet.
Får feilmeldingen:
OSError: Unable to communicate with the jupyter_dash notebook or JupyterLab
extension required to infer Jupyter configuration.

La også til en test som kjøres hvis man prøver å kjøre models_delt.py direkte